### ISSUE TITLE
I think the name of this project causes issues for windows users.

### ISSUE THREAD

**Issue by Matthew-Maclean** [SSheldon/nul#1] opened 2017-04-30 19:53 UTC
When cargo updates its crates.io registry, it creates a file for each crate, no extension, just the name.

The name `nul` is not a valid name in windows 10, so cargo fails to update the registry, and then aborts whatever it was doing (building, searching, ect.).

I think this project should be re-published to crates.io under a new name, something like `null-strings` perhaps?

**Comment by khaale** [comment] 2017-04-30 20:11
Causes https://github.com/rust-lang/cargo/issues/3982

**Comment by coder543** [comment] 2017-04-30 20:14
https://www.reddit.com/r/rust/comments/68hemz/i_think_a_crate_called_nul_is_causing_errors_for/

**Comment by coder543** [comment] 2017-04-30 20:14
Cargo is literally broken on Windows. Yanking the package might help, it might not.

**Comment by nagisa** [comment] 2017-04-30 20:25
Yanking will not help.

**Comment by retep998** [comment] 2017-04-30 21:03
The index has been screwed until someone manually commits to the index to remove the offending crate. Someone will also have to add code to crates.io to prevent such crates from ever being published.

**Comment by SSheldon** [comment] 2017-04-30 21:04
@carols10cents is deleting this crate from crates.io and I promise not to re-publish it under the same name 😄

**Comment by nelsonjchen** [comment] 2017-04-30 21:16
Can this repo even be cloned to Windows?

**Comment by lnicola** [comment] 2017-04-30 21:16
Yes, `git clone` works (but does not create the file).

**Comment by nelsonjchen** [comment] 2017-04-30 21:17
Ah, and there's also the workaround of having a different destination folder.

**Comment by ruabmbua** [comment] 2017-04-30 21:21
I am going to switch my windows development to linux...
I guess cross compiling is in the picture now?

**Comment by SSheldon** [comment] 2017-04-30 21:32
`nul` was removed from crates.io, so rust-lang/cargo#3982 is all fixed now. I've enjoyed our time together everyone, see you next time I manage to bring down crates.io 😊

**Closed as completed by SSheldon** 2017-04-30 21:32 UTC

**Comment by ruabmbua** [comment] 2017-04-30 21:35
Don`t you dare!

**Comment by matematikaadit** [comment] 2017-04-30 22:30
Congrats, you win the internet :+1:

**Comment by niamster** [comment] 2017-04-30 22:34
IMO it's a shame they forced you to delete the project. `cargo` should be fixed instead.

**Comment by retep998** [comment] 2017-04-30 22:39
@niamster The problem is that older versions of cargo need to work with newer versions of the index, so we can't just change how the index is structured without breaking older versions of cargo.

**Comment by coder543** [comment] 2017-04-30 22:41
@niamster arguably, fixing it *well* would require fixing Windows. It might be possible to hack around special names for each platform, but that would still be a hack. It's both easier and cleaner to just ban problematic names from the Crates registry. `cargo` *will be fixed* as well, but only to prevent the same issue from occurring in the future, but there's no good way to "fix" it such that `nul` is an acceptable name for a crate.

**Comment by retep998** [comment] 2017-04-30 22:47
Even if a new version of Windows came out that made breaking changes to how it resolves paths to "fix" this issue, or if cargo figured out how to use verbatim paths everywhere (especially inside libgit2) to avoid that problematic path resolution, we'd still have to worry about all the people using older versions, so we'd never be able to allow such crate names on crates.io (unless we migrated to a new index with a newer cargo version which could cause a catastrophic ecosystem split).

**Comment by niamster** [comment] 2017-04-30 22:47
@retep998 @coder543 There's always a good way to keep backward compatibility. I understand that changing that isn't easy and not obvious. Blacklisting names is the a hack by itself.
